### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by mossti** [coltonriedel/cracl#21]
Hello! I'm attempting to use this package on a Raspberry Pi Zero W running Raspbian Buster and am encountering an inheritance error in the file _device.hpp_ on build.

Namely, the _~basic_serial_port()_ and _~io_service_ destructors are throwing errors about not having types prior to the '(' symbol. I've tried to explicitly include boost/asio in my libraries and am at a bit of a loss.

These errors occur whether I am trying to build the standalone cracl library or when including source and header files in my project.

Thank you for your library and for your time!
--mossti

**Comment by coltonriedel** [comment]
thanks for creating an issue

hopefully the only problem is that I have the architecture hard coded in the Makefile

unfortunately I can't replicate your environment to test any changes, but @fefifofums has a Pi Zero and is going to check into it

**Comment by coltonriedel** [comment]
[Potentially related](https://github.com/boostorg/asio/blob/develop/include/boost/asio/serial_port.hpp#L21)

**Comment by fefifofums** [comment]
@mossti give the arm_pizero branch a try.  I compiled cracl with g++ versions 6.5, 7.3, 8.3 (default for me) on a  Raspberry Pi Zero W V1.1 running Raspbian Buster July 2019, with Boost 1.67.  

The issue appeared to be with the type lookup system for gcc-arm.   Fully naming the type seemed to fix the issue.  Hope this help, good luck with your project.

**Comment by mossti** [comment]
Thank you @coltonriedel and @fefifofums for the prompt, detailed, and extremely helpful response! I'm pretty new to embedded systems (~8 months in!) and this kind of developer support is super encouraging.

I'm going to try out the arm_pizero branch today and I'll let you know ASAP how it goes!

**Comment by coltonriedel** [comment]
no problem, I'm glad that someone else can find the code useful

some other suggestions: 
- there is a parameter called `max_handlers` which corresponds to maximum number of event (e.g. a read) handlers allowed to accumulate for the serial port. The default value is 100k; I don't remember what this corresponds to in terms of actual size, but if your RAM use is too high on the pi you might need to lower it
- assuming you're using a uBlox and depending on how you're using it you might want to increase the measurement and/or navigation rate (UBX-CFG-RATE). IIRC the default navigation rate is 1Hz and aligned with UTC. We use it mostly for data logging, so the potential latency between solutions is fine since they are time stamped anyways

good luck!

**Comment by mossti** [comment]
Thank you so much for the additional tips! And yep, I am using the uBlox F9P. The arm_pizero branch compiled without errors! I'm going to see how the new package works implemented into our project, but for now I feel comfortable closing this issue. Thanks again for the excellent dev support!

All the best,
Andrew

**Comment by coltonriedel** [comment]
Update: I was setting LDFLAGS for what seems to be no reason, breaking portability. Leaving it out appears to work just fine. There was still a separate issue with resolving the destructors, but both fixes are now on the master branch
